name: Lint Files

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  line_endings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check line endings
        run: |
          (find . -name \*.md | xargs file | grep CRLF) && (echo "Files contain CRLF line endings!"; exit 1)
